//
//  GrocerySections.swift
//  Ganguru_GroceryApp
//
//  Created by student on 4/6/22.
//

import Foundation

struct GrocerySections {
    var section = ""
    var items_Array:[GroceryItem] = []
}

struct GroceryItem {
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let section1 = GrocerySections(section:"Meat & SeaFood",items_Array: [ GroceryItem(itemName:"Chicken",itemImage:"chicken",itemInfo:"Chicken is the most common type of poultry in the world. Owing to the relative ease and low cost of raising chickens."), GroceryItem(itemName:"Turkey",itemImage:"turkey",itemInfo:"Turkey meat, commonly referred to as just turkey, is the meat from turkeys, typically domesticated turkeys but also wild turkeys."),GroceryItem(itemName:"Mutton",itemImage:"mutton",itemInfo:"Lamb, hogget, and mutton, generically sheep meat, are the meat of domestic sheep, Ovis aries. A sheep in its first year is a lamb and its meat is also lamb. "),GroceryItem(itemName:"Fish",itemImage:"fish",itemInfo:"Many species of fish are caught by humans and consumed as food in virtually all regions around the world. Fish has been an important dietary source of protein and other nutrients throughout human history."),GroceryItem(itemName:"Shrimp",itemImage:"shrimp",itemInfo:"Shrimp and prawn are types of seafood that are consumed worldwide. Although shrimp and prawns belong to different suborders of Decapoda, they are very similar in appearance."),GroceryItem(itemName:"Pork",itemImage:"pork",itemInfo:"Pork is the culinary name for the meat of the domestic pig. It is the most commonly consumed meat worldwide, with evidence of pig husbandry dating back to 5000 BC.")]);

let section2 = GrocerySections(section:"Vegetables",items_Array: [ GroceryItem(itemName:"Tomato",itemImage:"tomato",itemInfo:"The tomato is the edible berry of the plant Solanum lycopersicum, commonly known as the tomato plant. The species originated in western South America and Central America."), GroceryItem(itemName:"Okra",itemImage:"okra",itemInfo:"Okra or Okro, Abelmoschus esculentus, known in many English-speaking countries as ladies' fingers or ochro, is a flowering plant in the mallow family. Its edible green seed pods are a food. "),GroceryItem(itemName:"Cucumber",itemImage:"cucumber",itemInfo:"Cucumber is a widely-cultivated creeping vine plant in the Cucurbitaceae family that bears usually cylindrical fruits, which are used as vegetables. "),GroceryItem(itemName:"Spinach",itemImage:"spinach",itemInfo:"Spinach is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae."),GroceryItem(itemName:"Luffa",itemImage:"luffa",itemInfo:"Luffa is a genus of tropical and subtropical vines in the cucumber family. In everyday non-technical usage, the luffa, also spelled loofah, usually refers to the fruits of the species."),GroceryItem(itemName:"Potato",itemImage:"potato",itemInfo:"The potato is a starchy tuber of the plant Solanum tuberosum and is a root vegetable native to the Americas. The plant is a perennial in the nightshade family Solanaceae.")]);

let section3 = GrocerySections(section:"Fruits",items_Array: [ GroceryItem(itemName:"Apple",itemImage:"apple",itemInfo:"An apple is an edible fruit produced by an apple tree. Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus."), GroceryItem(itemName:"Banana",itemImage:"banana",itemInfo:"A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa"),GroceryItem(itemName:"Orange",itemImage:"orange",itemInfo:"An orange is a fruit of various citrus species in the family Rutaceae; it primarily refers to Citrus × sinensis, which is also called sweet orange, to distinguish it from the related Citrus × aurantium, referred to as bitter orange."),GroceryItem(itemName:"Avocado",itemImage:"avocado",itemInfo:"The avocado is a tree originating in the Americas which is likely native to the highland regions of south-central Mexico to Guatemala. It is classified as a member of the flowering plant family Lauraceae"),GroceryItem(itemName:"Watermelon",itemImage:"watermelon",itemInfo:"Watermelon is grown in favorable climates from tropical to temperate regions worldwide for its large edible fruit, which is a berry with a hard rind."),GroceryItem(itemName:"Guava",itemImage:"guava",itemInfo:"Guavas are tropical trees originating in Central America. Their fruits are oval in shape with light green or yellow skin and contain edible seeds. What's more, guava leaves are used as an herbal tea and the leaf extract as a supplement."),GroceryItem(itemName:"Muskmelon",itemImage:"musk",itemInfo:"Cucumis melo, also known as melon, is a species of Cucumis that has been developed into many cultivated varieties. The fruit is a pepo.")]);

let section4 = GrocerySections(section:"Ice Creams",items_Array: [ GroceryItem(itemName:"Vanila",itemImage:"vanila",itemInfo:"Vanilla is frequently used to flavor ice cream, especially in North America, Asia, and Europe. Vanilla ice cream, like other flavors of ice cream, was originally created by cooling a mixture made of cream."), GroceryItem(itemName:"Chocolate",itemImage:"chocolate",itemInfo:"Chocolate ice cream is ice cream with natural or artificial chocolate flavoring."),GroceryItem(itemName:"Strawberry",itemImage:"strawberry",itemInfo:"Strawberry ice cream is a flavor of ice cream made with strawberry or strawberry flavoring. It is made by blending in fresh strawberries or strawberry flavoring with the eggs, cream, vanilla and sugar used to make ice cream"),GroceryItem(itemName:"Cookies & Cream",itemImage:"cookie",itemInfo:"Cookies and cream ice cream is a rich and creamy vanilla ice cream stuffed full of chunks of different types of cookies"),GroceryItem(itemName:"Oreo Cookie",itemImage:"oreo",itemInfo:"Cookies and cream ice cream is a rich and creamy vanilla ice cream stuffed full of chunks of Oreo cookies"),GroceryItem(itemName:"Butterscotch",itemImage:"butter",itemInfo:"Butterscotch is a type of confectionery whose primary ingredients are brown sugar and butter, but other ingredients are part of some recipes, such as corn syrup, cream, vanilla, and salt.")]);

let section5 = GrocerySections(section:"Beverages",items_Array: [ GroceryItem(itemName:"Coke",itemImage:"coke",itemInfo:"Coca-Cola, or Coke, is a carbonated soft drink manufactured by the Coca-Cola Company. Originally marketed as a temperance drink and intended as a patent medicine"), GroceryItem(itemName:"Sprite",itemImage:"sprite",itemInfo:"Sprite is a colorless, lemon and lime-flavored soft drink created by The Coca-Cola Company. It was first developed in West Germany in 1959 as Fanta Klare Zitrone and was introduced in the United States"),GroceryItem(itemName:"Bodyarmour",itemImage:"body",itemInfo:"BODYARMOR is a premium sports drink that provides superior hydration. It is packed with electrolytes, coconut water and vitamins and is low in sodium and high in potassium."),GroceryItem(itemName:"RedBull",itemImage:"redbull",itemInfo:"Red Bull is a brand of energy drinks sold by Austrian company Red Bull GmbH. With 38% market share, it is the most popular energy drink brand as of 2019."),GroceryItem(itemName:"Mocktail",itemImage:"mocktail",itemInfo:"A non-alcoholic mixed drink is a cocktail-style beverage made without alcoholic ingredients. Also called zero proof drinks, the non-alcoholic drink dates back to the earliest days of the cocktail age."),GroceryItem(itemName:"Modelo",itemImage:"modelo",itemInfo:"Casa Modelo is the house of authentic Mexican beer. Discover Modelo Especial, Modelo Negra & Chelada and their unique flavors and story.")]);

let groceries = [section1,section2,section3,section4,section5]

